[2022-02-16 17:04:39,710] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.task_a scheduled__2022-02-15T00:00:00+00:00 [queued]>
[2022-02-16 17:04:39,719] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.task_a scheduled__2022-02-15T00:00:00+00:00 [queued]>
[2022-02-16 17:04:39,719] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-16 17:04:39,719] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-16 17:04:39,719] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-16 17:04:39,732] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): task_a> on 2022-02-15 00:00:00+00:00
[2022-02-16 17:04:39,735] {standard_task_runner.py:52} INFO - Started process 2417 to run task
[2022-02-16 17:04:39,740] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'task_a', 'scheduled__2022-02-15T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmps_1exz2n', '--error-file', '/tmp/tmp6zak7v90']
[2022-02-16 17:04:39,741] {standard_task_runner.py:77} INFO - Job 2: Subtask task_a
[2022-02-16 17:04:39,800] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.task_a scheduled__2022-02-15T00:00:00+00:00 [running]> on host f8b49ae6ae82
[2022-02-16 17:04:40,239] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=task_a
AIRFLOW_CTX_EXECUTION_DATE=2022-02-15T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-15T00:00:00+00:00
[2022-02-16 17:04:40,239] {logging_mixin.py:109} INFO - Done
[2022-02-16 17:04:40,239] {python.py:175} INFO - Done. Returned value was: None
[2022-02-16 17:04:40,257] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=task_a, execution_date=20220215T000000, start_date=20220216T170439, end_date=20220216T170440
[2022-02-16 17:04:40,320] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-16 17:04:40,379] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
