[2022-02-19 06:38:34,441] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: demo_etl.Load_Data.Save_to_DB manual__2022-02-19T06:38:13.192482+00:00 [queued]>
[2022-02-19 06:38:34,453] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: demo_etl.Load_Data.Save_to_DB manual__2022-02-19T06:38:13.192482+00:00 [queued]>
[2022-02-19 06:38:34,453] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 06:38:34,453] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-19 06:38:34,453] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 06:38:34,469] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): Load_Data.Save_to_DB> on 2022-02-19 06:38:13.192482+00:00
[2022-02-19 06:38:34,477] {standard_task_runner.py:52} INFO - Started process 36536 to run task
[2022-02-19 06:38:34,483] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'demo_etl', 'Load_Data.Save_to_DB', 'manual__2022-02-19T06:38:13.192482+00:00', '--job-id', '273', '--raw', '--subdir', 'DAGS_FOLDER/demo_etl.py', '--cfg-path', '/tmp/tmpdx9uep0a', '--error-file', '/tmp/tmpoz5ejgpp']
[2022-02-19 06:38:34,484] {standard_task_runner.py:77} INFO - Job 273: Subtask Load_Data.Save_to_DB
[2022-02-19 06:38:34,574] {logging_mixin.py:109} INFO - Running <TaskInstance: demo_etl.Load_Data.Save_to_DB manual__2022-02-19T06:38:13.192482+00:00 [running]> on host c39e331ab017
[2022-02-19 06:38:34,636] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=demo_etl
AIRFLOW_CTX_TASK_ID=Load_Data.Save_to_DB
AIRFLOW_CTX_EXECUTION_DATE=2022-02-19T06:38:13.192482+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-19T06:38:13.192482+00:00
[2022-02-19 06:38:34,643] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-02-19 06:38:34,644] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-02-19 06:38:34,645] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-02-19 06:38:34,646] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-02-19 06:38:34,647] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-02-19 06:38:34,648] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-02-19 06:38:34,649] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-02-19 06:38:34,649] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-02-19 06:38:34,651] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-02-19 06:38:34,652] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-02-19 06:38:34,652] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-02-19 06:38:34,653] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-02-19 06:38:34,709] {logging_mixin.py:109} INFO - Done !!
[2022-02-19 06:38:34,908] {logging_mixin.py:109} INFO - Done !!
[2022-02-19 06:38:34,980] {logging_mixin.py:109} INFO -       VendorID lpep_pickup_datetime  ... trip_type  congestion_surcharge
0            2  2019-12-18 15:52:30  ...         1                     0
1            2  2020-01-01 00:45:58  ...         2                     0
2            2  2020-01-01 00:41:38  ...         1                     0
3            1  2020-01-01 00:52:46  ...         1                     2
4            1  2020-01-01 00:19:57  ...         1                     0
...        ...                  ...  ...       ...                   ...
3995         2  2021-01-02 12:48:43  ...         1                     0
3996         1  2021-01-02 12:16:47  ...         1                     0
3997         2  2021-01-02 12:07:17  ...         1                     0
3998         2  2021-01-02 12:32:45  ...         1                     0
3999         2  2021-01-02 12:02:46  ...         1                     0

[4000 rows x 18 columns]
[2022-02-19 06:38:37,206] {logging_mixin.py:109} INFO - Save Data to Database Done !!
[2022-02-19 06:38:37,207] {python.py:175} INFO - Done. Returned value was: None
[2022-02-19 06:38:37,218] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=demo_etl, task_id=Load_Data.Save_to_DB, execution_date=20220219T063813, start_date=20220219T063834, end_date=20220219T063837
[2022-02-19 06:38:37,265] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 06:38:37,307] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
