[2022-02-19 16:23:21,985] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: demo_etl.Clean_Data manual__2022-02-19T16:21:55.210923+00:00 [queued]>
[2022-02-19 16:23:21,995] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: demo_etl.Clean_Data manual__2022-02-19T16:21:55.210923+00:00 [queued]>
[2022-02-19 16:23:21,995] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 16:23:21,995] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-19 16:23:21,995] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 16:23:22,006] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): Clean_Data> on 2022-02-19 16:21:55.210923+00:00
[2022-02-19 16:23:22,011] {standard_task_runner.py:52} INFO - Started process 42819 to run task
[2022-02-19 16:23:22,016] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'demo_etl', 'Clean_Data', 'manual__2022-02-19T16:21:55.210923+00:00', '--job-id', '408', '--raw', '--subdir', 'DAGS_FOLDER/demo_etl.py', '--cfg-path', '/tmp/tmps_ufvsgk', '--error-file', '/tmp/tmp_x7a8al3']
[2022-02-19 16:23:22,017] {standard_task_runner.py:77} INFO - Job 408: Subtask Clean_Data
[2022-02-19 16:23:22,080] {logging_mixin.py:109} INFO - Running <TaskInstance: demo_etl.Clean_Data manual__2022-02-19T16:21:55.210923+00:00 [running]> on host d18a6d5a39bc
[2022-02-19 16:23:22,139] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=demo_etl
AIRFLOW_CTX_TASK_ID=Clean_Data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-19T16:21:55.210923+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-19T16:21:55.210923+00:00
[2022-02-19 16:23:22,140] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-19 16:23:22,196] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'find /opt/***/data -name "*.csv" -type f']
[2022-02-19 16:23:22,442] {subprocess.py:85} INFO - Output:
[2022-02-19 16:23:22,615] {subprocess.py:89} INFO - /opt/***/data/taxi_2021.csv
[2022-02-19 16:23:22,616] {subprocess.py:89} INFO - /opt/***/data/taxi_2020-2021.csv
[2022-02-19 16:23:22,616] {subprocess.py:89} INFO - /opt/***/data/taxi_2020.csv
[2022-02-19 16:23:22,617] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-19 16:23:22,650] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=demo_etl, task_id=Clean_Data, execution_date=20220219T162155, start_date=20220219T162321, end_date=20220219T162322
[2022-02-19 16:23:22,682] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 16:23:22,729] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
