[2022-02-19 13:43:22,506] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: demo_email.Send_Email manual__2022-02-19T13:43:18.299477+00:00 [queued]>
[2022-02-19 13:43:22,517] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: demo_email.Send_Email manual__2022-02-19T13:43:18.299477+00:00 [queued]>
[2022-02-19 13:43:22,517] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 13:43:22,517] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-19 13:43:22,517] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 13:43:22,530] {taskinstance.py:1259} INFO - Executing <Task(EmailOperator): Send_Email> on 2022-02-19 13:43:18.299477+00:00
[2022-02-19 13:43:22,535] {standard_task_runner.py:52} INFO - Started process 748 to run task
[2022-02-19 13:43:22,540] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'demo_email', 'Send_Email', 'manual__2022-02-19T13:43:18.299477+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/pandastest.py', '--cfg-path', '/tmp/tmpjb_slkh6', '--error-file', '/tmp/tmpzz59y5xy']
[2022-02-19 13:43:22,541] {standard_task_runner.py:77} INFO - Job 356: Subtask Send_Email
[2022-02-19 13:43:22,600] {logging_mixin.py:109} INFO - Running <TaskInstance: demo_email.Send_Email manual__2022-02-19T13:43:18.299477+00:00 [running]> on host d18a6d5a39bc
[2022-02-19 13:43:22,653] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=demo_email
AIRFLOW_CTX_TASK_ID=Send_Email
AIRFLOW_CTX_EXECUTION_DATE=2022-02-19T13:43:18.299477+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-19T13:43:18.299477+00:00
[2022-02-19 13:43:22,670] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:102 PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2022-02-19 13:43:22,670] {configuration.py:381} WARNING - section/key [smtp/smtp_user] not found in config
[2022-02-19 13:43:22,670] {email.py:208} INFO - Email alerting: attempt 1
[2022-02-19 13:43:22,754] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 88, in execute
    conn_id=self.conn_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 66, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 102, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 217, in send_mime_email
    conn.starttls()
  File "/usr/local/lib/python3.7/smtplib.py", line 757, in starttls
    "STARTTLS extension not supported by server.")
smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server.
[2022-02-19 13:43:22,798] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=demo_email, task_id=Send_Email, execution_date=20220219T134318, start_date=20220219T134322, end_date=20220219T134322
[2022-02-19 13:43:22,823] {standard_task_runner.py:92} ERROR - Failed to execute job 356 for task Send_Email
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 88, in execute
    conn_id=self.conn_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 66, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 102, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 217, in send_mime_email
    conn.starttls()
  File "/usr/local/lib/python3.7/smtplib.py", line 757, in starttls
    "STARTTLS extension not supported by server.")
smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server.
[2022-02-19 13:43:22,838] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-19 13:43:22,879] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
